"""
make_spec.py — generates PatoToolBot.spec for PyInstaller 6
Usage: python make_spec.py [upx_dir]   (the upx_dir argument is accepted for
       backwards compatibility but ignored — see the UPX note below.)
"""
import os, sys, torch

app_py    = os.path.abspath("app.py")
torch_lib = os.path.join(os.path.dirname(torch.__file__), "lib")
configs   = os.path.abspath("configs")
icon      = os.path.abspath("icon.ico")

if not os.path.isdir(torch_lib):
    print(f"ERROR: torch lib folder not found: {torch_lib}")
    sys.exit(1)

print(f"app.py    : {app_py}")
print(f"torch/lib : {torch_lib}")

# ── UPX is DISABLED on purpose ────────────────────────────────────────────────
# UPX-compressing PyTorch's native DLLs (c10.dll, torch_cpu.dll, ...) corrupts
# them, and the frozen app crashes with an access violation (0xc0000005 in
# c10.dll) the instant torch initializes — typically right after the OCR splash.
# The build is already small without UPX (CPU torch + no *.lib ≈ 450 MB), so we
# simply do not compress. Do not re-enable UPX without excluding the torch DLLs.
print("UPX       : disabled (corrupts torch DLLs)")
upx_enabled  = False
upx_dir_line = ""

# PyInstaller 6 rules:
#   Analysis(datas=...)    expects list of 2-tuples: (src, dest_dir)
#   Analysis(binaries=...) expects list of 2-tuples: (src, dest_dir)
#   collect_all()          is NOT an Analysis parameter — must be called manually
#                          and returns (datas, binaries, hiddenimports) as 2-tuple lists
#   COLLECT                receives a.binaries and a.datas which are already
#                          normalized to 3-tuples internally — do NOT pass raw tuples

spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by make_spec.py
import os as _os, glob as _glob
from PyInstaller.utils.hooks import collect_all

easyocr_datas, easyocr_bins, easyocr_hidden = collect_all('easyocr')
torch_datas,   torch_bins,   torch_hidden   = collect_all('torch')

# Drop link-time-only static libraries (*.lib) — they are used by the compiler/
# linker, never loaded at runtime. In the torch wheel these add ~800 MB of dead
# weight (dnnl.lib alone is ~620 MB).
def _no_static_lib(items):
    return [t for t in items if not str(t[0]).lower().endswith('.lib')]
torch_datas = _no_static_lib(torch_datas)
torch_bins  = _no_static_lib(torch_bins)

# Bundle only the runtime files from torch/lib (DLLs etc.), never the *.lib.
_torch_lib = {repr(torch_lib)}
torch_lib_bins = [(_f, 'torch/lib')
                  for _f in _glob.glob(_os.path.join(_torch_lib, '*'))
                  if _os.path.isfile(_f) and not _f.lower().endswith('.lib')]

a = Analysis(
    [{repr(app_py)}],
    pathex=[],
    binaries=torch_lib_bins + easyocr_bins + torch_bins,
    datas=[
        ({repr(configs)}, 'configs'),
    ] + easyocr_datas + torch_datas,
    hiddenimports=[
        'torch',
        'torch.cuda',
        'torch.backends.cudnn',
        'torchvision',
        'easyocr',
        'easyocr.easyocr',
        'cv2',
    ] + easyocr_hidden + torch_hidden,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PatoToolBot',
    icon={repr(icon)},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx={upx_enabled},
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx={upx_enabled},
{upx_dir_line}
    upx_exclude=[],
    name='PatoToolBot',
)
"""

out = "PatoToolBot.spec"
with open(out, "w", encoding="utf-8") as f:
    f.write(spec)
print(f"Spec written: {os.path.abspath(out)}")
